#!/bin/sh
# $Id: scull_load,v 1.4 2004/11/03 06:19:49 rubini Exp $
module="scull"
device="scull"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}[0-19]

a=0
while [ $a -ne 20 ]
do
    mknod /dev/${device}$a c $major $a
    #ln -sf ${device}$a /dev/${device}$a

    mknod /dev/${device}$a.labeled c $major $a.labeled
    #ln -sf ${device}$a.labeled /dev/${device}$a.labeled

    mknod /dev/${device}$a.relabeled c $major $a.relabeled　　
    
    a=`expr $a + 1`
done

chgrp $group /dev/${device}[0-19] 
chmod $mode  /dev/${device}[0-19]







