# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias e='emacs --color=no'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# HIST: The following 3 lines were added by nec setup script.
unset HISTCONTROL
HISTSIZE=20000
HISTTIMEFORMAT=" %F %T  "

export JAVA_HOME=/usr/java/jdk1.8.0_66                                                                                   
export HADOOP_HOME=/root/hadoop-2.7.1                                                                                    
export PATH=$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$JAVA_HOME/bin:$PATH                                
export PATH=$PATH:/root/pig-0.16.0/bin/        
